config/routes.rb
Rails.application.routes.draw do
  resources :user_ad_interactions
  resources :ad_types
  resources :interaction_types
  resources :donations
  resources :events
  resources :vouches
  resources :scenarios
  # jsonapi_resources :users
  resources :nouns
  resources :verbs

  jsonapi_resources :vouches
  jsonapi_resources :scenarios
  jsonapi_resources :nouns
  jsonapi_resources :verbs

  jsonapi_resources :users
  post 'users/verify' => "users#verify"

  get 'test' => "users#test"

  root to: "scenarios#index"

  get "/ad" => "scenarios#ad", as: "ad"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_ad_interactions_controller.rb
class UserAdInteractionsController < ApplicationController
  before_action :set_user_ad_interaction, only: %i[show edit update destroy]

  # GET /user_ad_interactions
  # GET /user_ad_interactions.json
  def index
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @user_ad_interactions = UserAdInteraction.all
    end
  end

  # GET /user_ad_interactions/1
  # GET /user_ad_interactions/1.json
  def show
    super if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
  end

  # GET /user_ad_interactions/new
  def new
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @user_ad_interaction = UserAdInteraction.new
    end
  end

  # GET /user_ad_interactions/1/edit
  def edit; end

  # POST /user_ad_interactions
  # POST /user_ad_interactions.json
  def create
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @user_ad_interaction = UserAdInteraction.new(user_ad_interaction_params)

      if @user_ad_interaction.save
        redirect_to @user_ad_interaction, notice: "UserAdInteraction was successfully created."
      else
        render :new
      end
    end
  end

  # PATCH/PUT /user_ad_interactions/1
  # PATCH/PUT /user_ad_interactions/1.json
  def update
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      if @user_ad_interaction.update(user_ad_interaction_params)
        redirect_to @user_ad_interaction, notice: "UserAdInteraction was successfully updated."
      else
        render :edit
      end
    end
  end

  # DELETE /user_ad_interactions/1
  # DELETE /user_ad_interactions/1.json
  def destroy
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @user_ad_interaction.destroy
      redirect_to user_ad_interactions_url, notice: "UserAdInteraction was successfully destroyed."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_ad_interaction
    @user_ad_interaction = UserAdInteraction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_ad_interaction_params
    params.require(:user_ad_interaction).permit(:description)
  end
end

app/helpers/user_ad_interactions_helper.rb
module UserAdInteractionsHelper
end

app/views/user_ad_interactions/_form.html.erb
<%= form_with(model: user_ad_interaction, local: true) do |form| %>
<% if user_ad_interaction.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user_ad_interaction.errors.count, "error") %>
      prohibited this user_ad_interaction from being saved:</h2>

    <ul>
      <% user_ad_interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :user_id %>
  <%= select("vouch", "user_id", User.all.collect {|u| [ u.name, u.id ] }, { }) %>
</div>

<div class="field">
  <%= form.label :interaction_type_id %>
  <%= select("vouch", "interaction_type_id", InteractionType.all.collect {|i| [ i.description, i.id ] }, { }) %>
</div>

<div class="field">
  <%= form.label :ad_type_id %>
  <%= select("vouch", "ad_type_id", AdType.all.collect {|a| [ a.description, a.id ] }, { }) %>
</div>

<div class="field">
  <%= form.label :scenario_id %>
  <%= select("vouch", "scenario_id", Scenario.all.collect {|s| [ s.description, s.id ] }, { }) %>
</div>


<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/user_ad_interactions/edit.html.erb
<h1>Editing User Ad Interaction</h1>

<%= render 'form', user_ad_interaction: @user_ad_interaction %>

<%= link_to 'Show', @user_ad_interaction %> |
<%= link_to 'Back', user_ad_interactions_path %>

app/views/user_ad_interactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Ad Interactions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Interaction type</th>
      <th>Ad type</th>
      <th>Scenario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_ad_interactions.each do |user_ad_interaction| %>
      <tr>
        <td><%= user_ad_interaction.user.name %></td>
        <td><%= user_ad_interaction.interaction_type.description %></td>
        <td><%= user_ad_interaction.ad_type.description %></td>
        <td><%= user_ad_interaction.scenario.description %></td>
        <td><%= link_to 'Show', user_ad_interaction %></td>
        <td><%= link_to 'Edit', edit_user_ad_interaction_path(user_ad_interaction) %></td>
        <td><%= link_to 'Destroy', user_ad_interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Ad Interaction', new_user_ad_interaction_path %>

app/views/user_ad_interactions/new.html.erb
<h1>New User Ad Interaction</h1>

<%= render 'form', user_ad_interaction: @user_ad_interaction %>

<%= link_to 'Back', user_ad_interactions_path %>

app/views/user_ad_interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_ad_interaction.user.name %>
</p>

<p>
  <strong>Interaction type:</strong>
  <%= @user_ad_interaction.interaction_type.description %>
</p>

<p>
  <strong>Ad type:</strong>
  <%= @user_ad_interaction.ad_type.description %>
</p>

<p>
  <strong>Scenario:</strong>
  <%= @user_ad_interaction.scenario.description %>
</p>

<%= link_to 'Edit', edit_user_ad_interaction_path(@user_ad_interaction) %> |
<%= link_to 'Back', user_ad_interactions_path %>