config/routes.rb
Rails.application.routes.draw do
  resources :user_ad_interactions
  resources :ad_types
  resources :interaction_types
  resources :donations
  resources :events
  resources :vouches
  resources :scenarios
  # jsonapi_resources :users
  resources :nouns
  resources :verbs

  jsonapi_resources :vouches
  jsonapi_resources :scenarios
  jsonapi_resources :nouns
  jsonapi_resources :verbs

  jsonapi_resources :users
  post 'users/verify' => "users#verify"

  get 'test' => "users#test"

  root to: "scenarios#index"

  get "/ad" => "scenarios#ad", as: "ad"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
# == Schema Information
#
# Table name: donations
#
#  id          :bigint           not null, primary key
#  amount      :decimal(16, 3)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  donator_id  :bigint
#  scenario_id :bigint
#
# Indexes
#
#  index_donations_on_donator_id   (donator_id)
#  index_donations_on_scenario_id  (scenario_id)
#
# Foreign Keys
#
#  fk_rails_...  (donator_id => users.id)
#  fk_rails_...  (scenario_id => scenarios.id)
#
class Donation < ApplicationRecord
  belongs_to :scenario
  belongs_to :donator, class_name: "User", inverse_of: :donated
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[show edit update destroy]

  # GET /donations
  # GET /donations.json
  def index
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @donations = Donation.all
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    super if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
  end

  # GET /donations/new
  def new
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @donation = Donation.new
    end
  end

  # GET /donations/1/edit
  def edit; end

  # POST /donations
  # POST /donations.json
  def create
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @donation = Donation.new(donation_params)

      if @donation.save
        redirect_to @donation, notice: "Donation was successfully created."
      else
        render :new
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      if @donation.update(donation_params)
        redirect_to @donation, notice: "Donation was successfully updated."
      else
        render :edit
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @donation.destroy
      redirect_to donations_url, notice: "Donation was successfully destroyed."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_donation
    @donation = Donation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def donation_params
    params.require(:donation).permit(:donator_id, :scenario_id, :amount)
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_with(model: donation, local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :donator_id %>
    <%= select("donation", "donator_id", User.all.collect {|u| [ u.name, u.id ] }, {}) %>
  </div>

  <div class="field">
    <%= form.label :scenario_id %>
    <%= select("donation", "scenario_id", Scenario.all.collect {|s| [ s.description  , s.id ] }, {}) %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :donation_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Donator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.donator.name %></td>

        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Donator:</strong>
  <%= @donation.donator.name %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>