config/routes.rb
Rails.application.routes.draw do
  resources :user_ad_interactions
  resources :ad_types
  resources :interaction_types
  resources :donations
  resources :events
  resources :vouches
  resources :scenarios
  # jsonapi_resources :users
  resources :nouns
  resources :verbs

  jsonapi_resources :vouches
  jsonapi_resources :scenarios
  jsonapi_resources :nouns
  jsonapi_resources :verbs

  jsonapi_resources :users
  post 'users/verify' => "users#verify"

  get 'test' => "users#test"

  root to: "scenarios#index"

  get "/ad" => "scenarios#ad", as: "ad"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scenario.rb
# == Schema Information
#
# Table name: scenarios
#
#  id                 :bigint           not null, primary key
#  custom_message     :string
#  funding_goal       :decimal(16, 3)
#  image_content_type :string
#  image_file_name    :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  doer_id            :bigint
#  event_id           :bigint
#  noun_id            :bigint
#  parent_scenario_id :bigint
#  requester_id       :bigint
#  verb_id            :bigint
#
# Indexes
#
#  index_scenarios_on_doer_id             (doer_id)
#  index_scenarios_on_event_id            (event_id)
#  index_scenarios_on_noun_id             (noun_id)
#  index_scenarios_on_parent_scenario_id  (parent_scenario_id)
#  index_scenarios_on_requester_id        (requester_id)
#  index_scenarios_on_verb_id             (verb_id)
#
# Foreign Keys
#
#  fk_rails_...  (doer_id => users.id)
#  fk_rails_...  (event_id => events.id)
#  fk_rails_...  (noun_id => nouns.id)
#  fk_rails_...  (parent_scenario_id => scenarios.id)
#  fk_rails_...  (requester_id => users.id)
#  fk_rails_...  (verb_id => verbs.id)
#
class Scenario < ApplicationRecord
  after_save do |ob|
    mqtt_me(ob)
  end

  belongs_to :verb
  belongs_to :noun
  belongs_to :event
  belongs_to :requester, class_name: "User", inverse_of: :requested, optional: true
  belongs_to :doer, class_name: "User", inverse_of: :done, optional: true
  belongs_to :parent_scenario, class_name: "Scenario", inverse_of: :children_scenario, optional: true

  # has_many :verifications, class_name: 'Vouches', dependent: :destroy, inverse_of: :scenario
  has_many :vouches, dependent: :destroy
  has_many :donations, dependent: :destroy
  has_many :children_scenario, class_name: "Scenario", dependent: :nullify, inverse_of: :parent_scenario, foreign_key: :parent_scenario_id
  has_many :user_ad_interactions, dependent: :destroy

  delegate :firstname, :lastname, :latitude, :longitude, to: :doer, prefix: true, allow_nil: true
  delegate :firstname, :lastname, :latitude, :longitude, to: :requester, prefix: true, allow_nil: true

  # has_many :ads

  has_attached_file :image, styles: {
    thumb: "100x100>",
    square: "200x200#",
    medium: "300x300>"
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}

  scope :examples_for_demo, -> { where("id in (1)") }

  def self.create_subtask(new_scenario, goal)
    Scenario.create(parent_scenario: new_scenario,
                    event: new_scenario.event,
                    requester: new_scenario.requester,
                    verb: Verb.find_or_create_by(description: goal[:verb]),
                    noun: Noun.find_or_create_by(description: goal[:noun]),
                    custom_message: goal[:custom_message])
  end

  def description
    verb.description + " " + noun.description + (requester ? " for " + requester.name : "") + " in " + event.description
  end

  def parent_description
    return if parent_scenario.nil?

    parent_scenario.description
  end

  def requesterlat
    requester&.latitude
  end

  def requesterlon
    requester&.longitude
  end

  def doerlat
    doer&.latitude
  end

  def doerlon
    doer&.longitude
  end

  def donated
    donations.sum(:amount)
  end

  def verified
    vouches.count.positive?
  end

  def ratings
    # get a list of ratings from all vouches for this scenario, and its parent scenario if its a child
    ratings = vouches.where("rating is not null").pluck :rating

    ratings += parent_scenario.ratings if is_child

    ratings
  end

  def ratio_for_user(user)
    # need to implement https://github.com/togglepro/pundit-resources or something for user
    # but lkets fake it for now
    # user = User.find(1) if user.nil?
    return 0 if user.nil?
    ratio = 0

    done = user.done.count
    dismissed = user.user_ad_interactions.count

    ratio = done / dismissed unless dismissed.zero?
    ratio
  end

  def is_parent
    parent_scenario.nil?
  end

  def is_child
    !is_parent
  end

  def is_complete
    !vouches.count.zero?
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: %i[show edit update destroy]
  # get/materials", "get/transportation", "patch/roof", and "fix/roof"

  @@subtask_goals = [{ verb: "organise", noun: "materials", custom_message: "Organise materials" },
                     { verb: "collect", noun: "donations", custom_message: "Collect donations for materials" },
                     { verb: "pick up", noun: "volunteer labour", custom_message: "Pick up volunteer labour" },
                     { verb: "pick up", noun: "materials", custom_message: "Pick up materials" },
                     { verb: "patch", noun: "roof", custom_message: "Patch Roof" },
                     { verb: "paint and seal", noun: "roof", custom_message: "Paint & Seal Roof" }]

  # GET /scenarios
  # GET /scenarios.json
  def index
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @scenarios = Scenario.all
    end
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    super if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
  end

  def ad
    # authorize :admin_ad, :show?

    @example_scenarios = Scenario.examples_for_demo
    # binding.pry
    # <%= Verbs::Conjugator.conjugate scenario.verb.description.to_sym tense: :present, person: :second, plurality: :singular, aspect: :perfective %>

    respond_to do |format|
      format.html { render "ad" }
    end
  end

  # GET /scenarios/new
  def new
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @scenario = Scenario.new
    end
  end

  # GET /scenarios/1/edit
  def edit; end

  # POST /scenarios
  # POST /scenarios.json
  def create
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      Scenario.transaction do
        super
        new_scenario = Scenario.find(JSON.parse(response.body).dig("data", "id"))

        @@subtask_goals.each { |goal| Scenario.create_subtask(new_scenario, goal) }
      end
    else
      @scenario = Scenario.new(scenario_params)

      if @scenario.save
        redirect_to @scenario, notice: "Scenario was successfully created."
      else
        render :new
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    elsif @scenario.update(scenario_params)
      redirect_to @scenario, notice: "Scenario was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    if request.headers["HTTP_ACCEPT"] == "application/vnd.api+json"
      super
    else
      @scenario.destroy
      redirect_to scenarios_url, notice: "Scenario was successfully destroyed."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_scenario
    @scenario = Scenario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def scenario_params
    params.require(:scenario).permit(:verb_id, :noun_id, :requester_id, :doer_id, :image, :funding_goal, :event_id, :parent_scenario_id, :is_parent, :is_child, :custom_message)
  end
end

app/views/scenarios/_ad_doer.html.erb
<!-- shows the data from a scenario as an ad targeted as a doer, someone who can perform the task in the scenario -->

<div id="<%= "lion_ad_content_#{scenario.id}_do" %>">
  <%= render 'ad_profile_header' %>

  <p class="subheader">Help
    <%= scenario.doer_firstname.capitalize if scenario.doer %>
    <%= scenario.verb.description %>
    <%= scenario.noun.description %>
    for
    <%= scenario.requester_firstname.capitalize if scenario.requester %>
  </p>

  <%= render 'ad_image', image: scenario.image.url(:medium) %>

  <h1>Can you <%= "#{scenario.verb.description} #{scenario.requester_firstname.capitalize if scenario.requester}'s #{scenario.noun.description}" %>?</h1>

  <h2 class="location">Pearlington, Mississippi</h2>

  <p class="custom-message">Audrey's roof blew off in Hurricane Katrina and it needs patching. Can you please help her fix it?</p>

  <%= link_to("https://lion-frontend-uat.herokuapp.com/#{scenario.id}/doer/") do %>See on LION<% end %>


  <div class="share-bar">
    <div class="share-bar-left">
      <img class="share-bar-icon" src="<%= asset_path( 'reaction1.png' ) %>" />
      <img class="share-bar-icon" src="<%= asset_path( 'reaction2.png' ) %>" />
      <img class="share-bar-icon" src="<%= asset_path( 'reaction3.png' ) %>" />
    </div>
    <div class="share-bar-right">
      <span>200 Comments  </span>
      <span>35 Shares</span>
    </div>
  </div>
</div>

app/views/scenarios/_ad_donator.html.erb
<!-- shows the data from a scenario as an ad targeted as a doer, someone who can perform the task in the scenario -->

<div id="<%= "lion_ad_content_#{scenario.id}_donate" %>">
  <%= render 'ad_profile_header' %>

  <p class="subheader">Can you donate to help 
    <%= scenario.doer_firstname.capitalize if scenario.doer %>
    <%= scenario.verb.description %>
    <%= scenario.noun.description %>
    for
    <%= scenario.requester_firstname.capitalize if scenario.requester %>?
  </p>

  <%= render 'ad_image', image: scenario.image.url(:medium) %>

  <h1>Donate $2 to <%= "#{scenario.verb.description} #{scenario.requester_firstname.capitalize if scenario.requester}'s #{scenario.noun.description}" %>!</h1>

  <h2 class="location">Pearlington, Mississippi</h2>

  <p class="custom-message">Audrey's roof blew off in Hurricane Katrina and it needs patching. Can you please help her fix it?</p>

  <%= link_to("https://lion-frontend-uat.herokuapp.com/#{scenario.id}/donator/") do %>See on LION<% end %>




  <div class="share-bar">
    <div class="share-bar-left">
      <img class="share-bar-icon" src="<%= asset_path( 'reaction1.png' ) %>" />
      <img class="share-bar-icon" src="<%= asset_path( 'reaction2.png' ) %>" />
      <img class="share-bar-icon" src="<%= asset_path( 'reaction3.png' ) %>" />
    </div>
    <div class="share-bar-right">
      <span>200 Comments  </span>
      <span>35 Shares</span>
    </div>
  </div>
</div>

app/views/scenarios/_ad_image.html.erb
<figure class="image-wrap">
  <%= image_tag image, :class => "main-image" %>
  <figcaption class="image-caption">
    <div>3,445 views</div>
  </figcaption>
</figure>

app/views/scenarios/_ad_profile_header.html.erb
<header class="profile">
  <img class="profile-icon" src="<%= asset_path( 'fb-profile.jpg' ) %>" />
  <div class="profile-name highlight">Lion</div>
  <div class="profile-filler">shared <span class="highlight">a post</span></div>
  <div class="profile-footer">2hrs</div>
</header>

app/views/scenarios/_ad_requester.html.erb
<!-- shows the data from a scenario as an ad targeted as a doer, someone who can perform the task in the scenario -->

<div id="<%= "lion_ad_content_#{scenario.id}_request" %>">
  <%= render 'ad_profile_header' %>

  <p class="subheader">Do you need help with something?</p>

  <%= render 'ad_image', image: scenario.image.url(:medium) %>

  <h1><%= "Need #{scenario.noun.description} #{scenario.verb.description}ed?" %></h1>

  <h2 class="location">Pearlington, Mississippi</h2>

  <p class="custom-message">Audrey's roof blew off in Hurricane Katrina and it needs patching. Can you please help her fix it?</p>

  <%= link_to("https://lion-frontend-uat.herokuapp.com/#{scenario.id}/requester/") do %>See on LION<% end %>

  <div class="share-bar">
    <div class="share-bar-left">
      <img class="share-bar-icon" src="<%= asset_path( 'reaction1.png' ) %>" />
      <img class="share-bar-icon" src="<%= asset_path( 'reaction2.png' ) %>" />
      <img class="share-bar-icon" src="<%= asset_path( 'reaction3.png' ) %>" />
    </div>
    <div class="share-bar-right">
      <span>200 Comments  </span>
      <span>35 Shares</span>
    </div>
  </div>
</div>

app/views/scenarios/_ad_requestor.html.erb
<!-- shows the data from a scenario as an ad targeted as a doer, someone who can perform the task in the scenario -->
<div class="ad">

  <h1>Requestor Ad</h1>

  <%= image_tag scenario.image.url(:medium) %>

  <p>Do you need help with something?
    <%= scenario.requestor.name %>
    got help with
    <%= scenario.verb.description.verb.conjugate tense: :past, person: :third, plurality: :singular, aspect: :perfective %>
    <%= scenario.noun.description %>
    during
    <%= scenario.event.description if scenario.event %>.
  </p>

  <%= link_to 'Yes I Can', scenarios_path %>
</div>

app/views/scenarios/_ad_verifier.html.erb
<!-- shows the data from a scenario as an ad targeted as a doer, someone who can perform the task in the scenario -->
<div id="<%= "lion_ad_content_#{scenario.id}_verify" %>">
  <%= link_to("https://lion-frontend-uat.herokuapp.com/#{scenario.id}/verifier/") do %>
    <%= render 'ad_profile_header' %>

    <%= image_tag scenario.image.url(:medium), :class => "main-image" %>

    <h1>Help us verify <%= scenario.requester.firstname.slice(0,1).capitalize + scenario.requester.firstname.slice(1..-1) if scenario.requester %></h1>

    <h2><%= scenario.event.description  if scenario.event %></h2>

    <p>Are you able to verify that
      <%= scenario.doer.firstname.slice(0,1).capitalize + scenario.doer.firstname.slice(1..-1) if scenario.doer %>
      <%= scenario.verb.description %>
      <%= scenario.noun.description %>
      for
      <%= scenario.requester.firstname.slice(0,1).capitalize + scenario.requester.firstname.slice(1..-1) if scenario.requester %>?
    </p>

    <div class="location">
      <img class="location-icon" src="<%= asset_path( 'map-pin.png' ) %>" />
      <% if scenario.event.location_name then %>
        <span> <%= scenario.event.location_name %></span>
      <% else %>
        <span> <%= scenario.requesterlat %>, <%= scenario.requesterlon %></span>
      <% end %>
    </div>
    <div class="progress-bar">
      <input class="progress-bar-slider" type="range" min="0" max="<%= scenario.funding_goal %>" value="<%= scenario.donated %>" disabled>
    </div>
    <div class="progress-data">
      <div><b>$<%= scenario.donated.to_i %></b> funded</div>
    </div>
    <div class="share-bar">
      <div class="share-bar-left">
        <img class="share-bar-icon" src="<%= asset_path( 'reaction1.png' ) %>" />
        <img class="share-bar-icon" src="<%= asset_path( 'reaction2.png' ) %>" />
        <img class="share-bar-icon" src="<%= asset_path( 'reaction3.png' ) %>" />
      </div>
      <div class="share-bar-right">
        <span>200 Comments  </span>
        <span>35 Shares</span>
      </div>
    </div>
  <% end %>
</div>

app/views/scenarios/_form.html.erb
<%= form_with(model: scenario, local: true) do |form| %>
<% if scenario.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(scenario.errors.count, "error") %>
      prohibited this scenario from being saved:</h2>

    <ul>
      <% scenario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :verb_id %>
  <%= select("scenario", "verb_id", Verb.all.collect {|v| [ v.description, v.id ] }, {}) %>
</div>

<div class="field">
  <%= form.label :noun_id %>
  <%= select("scenario", "noun_id", Noun.all.collect {|n| [ n.description, n.id ] }, {}) %>
</div>

<div class="field">
  <%= form.label :requester_id %>
  <%= select("scenario", "requester_id", User.all.collect {|u| [ u.name, u.id ] }, { include_blank: true }) %>
</div>

<div class="field">
  <%= form.label :doer_id %>
  <%= select("scenario", "doer_id", User.all.collect {|u| [ u.name, u.id ] }, { include_blank: true }) %>
</div>

<div class="field">
  <%= form.label :event_id %>
  <%= select("scenario", "event_id", Event.all.collect {|e| [ e.description, e.id ] }, {}) %>
</div>

<div class="field">
  <%= form.label :funding_goal %>
  <%= form.text_field :funding_goal, id: :scenario_funding_goal %>
</div>

<div class="field">
  <%= form.label :custom_message %>
  <%= form.text_field :custom_message, id: :scenario_custom_message %>
</div>

<div class="field">
  <%= form.label :parent_scenario_id %>
  <%= select("scenario", "parent_scenario_id", Scenario.all.collect {|s| [ s.description, s.id ] }, { include_blank: true }) %>
</div>

<div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/scenarios/_scenario_table_row.html.erb
<tr>
  <td><%= scenario.id %></td>
  <td><%= image_tag scenario.image.url(:thumb) %></td>

  <td><%= scenario.verb.description %></td>
  <td><%= scenario.noun.description %></td>
  <td><%= scenario.requester.name if scenario.requester%></td>
  <td><%= scenario.doer.name if scenario.doer%></td>
  <td><%= scenario.funding_goal %></td>
  <td><%= scenario.parent_description %></td>
  <td><%= scenario.event.description %></td>
  <td><%= scenario.verified %></td>

  <td><%= link_to 'Show', scenario %></td>
  <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
  <td><%= link_to 'Destroy', scenario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/scenarios/ad.html.erb
<h1>Outreach Ads</h1>

  <p class="lion-ad-content">
    Donor ad targetting:
    <%= render 'ad_donator', scenario:  @example_scenarios[0] %>
  </p>
  <p class="lion-ad-content">
    ReQuester ad targetting:
    <%= render 'ad_requester', scenario:  @example_scenarios[0] %>
  </p>
  <p class="lion-ad-content">
    Do-er ad targetting:
    <%= render 'ad_doer', scenario:  @example_scenarios[0] %>
  </p>

<p>
  <%= link_to 'Back', scenarios_path %>
</p>

app/views/scenarios/edit.html.erb
<h1>Editing Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenarios</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Image</th>
      <th>Verb</th>
      <th>Noun</th>
      <th>requester</th>
      <th>Doer</th>
      <th>Funding Goal</th>
      <th>Is Child Of</th>
      <th>Event</th>
      <th>Verified as complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <%= render 'scenario_table_row', scenario: scenario %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scenario', new_scenario_path %>

app/views/scenarios/new.html.erb
<h1>New Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @scenario.image.url(:medium) %>

<p>
  <strong>Verb:</strong>
  <%= @scenario.verb.description %>
</p>

<p>
  <strong>Noun:</strong>
  <%= @scenario.noun.description %>
</p>

<p>
  <strong>requester:</strong>

  <% if @scenario.requester then %>
    <%= @scenario.requester.name %>
    <br>
    <%= image_tag @scenario.requester.avatar(:thumb) %>
  <% else %>
    None
  <% end %>
</p>

<p>
  <strong>Doer:</strong>
  <% if @scenario.doer then %>
    <%= @scenario.doer.name %>
    <br>
    <%= image_tag @scenario.doer.avatar(:thumb)  %>
  <% else %>
    None
  <% end %></p>

<p>
  <strong>event:</strong>
  <%= @scenario.event.description %>
</p>

<p>
  <strong>Funding Goal:</strong>
  <%= @scenario.funding_goal %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @scenario.verified %>
</p>

<p>
  <strong>Custom Message:</strong>
  <%= @scenario.custom_message %>
</p>

<p>
  <strong>Is Child Of:</strong>
  <br/>
  <% if @scenario.parent_scenario then %>
    <%= render 'scenario_table_row_short', scenarios: [ @scenario.parent_scenario ] %>
  <% else %>
    None
  <% end %>
</p>

<p>
  <strong>Is Parent Of:</strong>
  <br/>

  <% if @scenario.children_scenario.count != 0 then %>
    <%= render 'scenario_table_row_short', scenarios: @scenario.children_scenario %>
  <% else %>
    None
  <% end %>
</p>

<%= link_to 'Edit', edit_scenario_path(@scenario) %>
|
<%= link_to 'Back', scenarios_path %>