config/routes.rb
Rails.application.routes.draw do
  resources :user_ad_interactions
  resources :ad_types
  resources :interaction_types
  resources :donations
  resources :events
  resources :vouches
  resources :scenarios
  # jsonapi_resources :users
  resources :nouns
  resources :verbs

  jsonapi_resources :vouches
  jsonapi_resources :scenarios
  jsonapi_resources :nouns
  jsonapi_resources :verbs

  jsonapi_resources :users
  post 'users/verify' => "users#verify"

  get 'test' => "users#test"

  root to: "scenarios#index"

  get "/ad" => "scenarios#ad", as: "ad"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      </li>
    <% else %>
      <li>
        <%= link_to('Login', new_user_session_path) %>
      </li>
    <% end %>

    <p>
      <%= link_to 'Scenarios', scenarios_path %>
      <%= link_to 'Vouches', vouches_path %>
      <%= link_to 'Verbs', verbs_path %>
      <%= link_to 'Nouns', nouns_path %>
      <%= link_to 'Ads', ad_path %>
      <%= link_to 'Events', events_path %>
      <%= link_to 'Donations', donations_path %>
      <%= link_to 'Ad Types', ad_types_path %>
      <%= link_to 'Interaction Types', interaction_types_path %>
      <%= link_to 'User Ad Interactions', user_ad_interactions_path %>

    </p>
    <%= yield %>
  </body>
</html>